name: Commit check

on: [push, pull_request]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: |
           sudo apt-get -y install flex libfl-dev texlive-latex-base texlive-fonts-recommended

      - name: Build checkpd
        working-directory: Tools/pd
        run: make

      - name: Build checkusing
        working-directory: Tools/usingcheck
        run: make

      - name: Get changed C/C++ files
        id: changed-files-specific
        uses: tj-actions/changed-files@v11.9
        with:
           files:
              .(c|cpp|cxx|h|hpp|hxx)$

      - name: Process all modified source files
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE/Tools/usingcheck
          export PATH=$PATH:$GITHUB_WORKSPACE/Tools/pd
          export PD_HEADER=$GITHUB_WORKSPACE/Tools/pd/pd.header
          for file in ${{ steps.changed-files-specific.outputs.all_modified_files }}; do
            echo "$file was modified"
            ./Tools/usingcheck/usingcheck $file
            ./Tools/pd/checkpd $file
          done


